version: '3'

services:
  data:
    build: ./data-dump.sql
  mysql:
    image: mysql:latest
    container_name: mysql_server
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: vendas
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: mysql
    volumes:
      - ./.devops/mysql:/var/lib/mysql
    networks:
      - stack-network

  frontvuecli:
    build: ./frontvuecli/
    container_name: front_node_server
    ports:
      - "8080:8080"
    networks:
      - stack-network

  backnode:
    build: ./backnode/
    container_name: back_node_server
    ports:
      - "5000:5000"
    networks:
      - stack-network
    depends_on:
      - mysql

networks:
  stack-network:
    driver: bridge
